const DEFAULT_MAXES={bs:112,fs:100,sn:0,cj:0};
let trainingMaxes={
  bs:Number(localStorage.getItem("wl_max_bs")||DEFAULT_MAXES.bs),
  fs:Number(localStorage.getItem("wl_max_fs")||DEFAULT_MAXES.fs),
  sn:Number(localStorage.getItem("wl_max_sn")||DEFAULT_MAXES.sn),
  cj:Number(localStorage.getItem("wl_max_cj")||DEFAULT_MAXES.cj)
};
function round25(x){return Math.round(x/2.5)*2.5}
function fmtKg(x){if(!Number.isFinite(x))return"";return (Math.round(x*10)%10===0?Math.round(x):x.toFixed(1))+" kg"}
function initMaxInputs(){
  document.getElementById("maxBS").value=trainingMaxes.bs||"";
  document.getElementById("maxFS").value=trainingMaxes.fs||"";
  document.getElementById("maxSN").value=trainingMaxes.sn||"";
  document.getElementById("maxCJ").value=trainingMaxes.cj||"";
  updateMaxSummary();
}
function updateMaxSummary(){const sn=trainingMaxes.sn?` · Snatch ${trainingMaxes.sn} kg`:"";const cj=trainingMaxes.cj?` · C&J ${trainingMaxes.cj} kg`:"";document.getElementById("maxSummary").textContent=`BS ${trainingMaxes.bs} kg · FS ${trainingMaxes.fs} kg${sn}${cj} · 12周自动计划`}
function applyMaxes(){const bs=Number(document.getElementById("maxBS").value),fs=Number(document.getElementById("maxFS").value),sn=Number(document.getElementById("maxSN").value)||0,cj=Number(document.getElementById("maxCJ").value)||0;if(!(bs>0)||!(fs>0)){alert("Back Squat 和 Front Squat Max 需要大于 0");return}trainingMaxes={bs,fs,sn,cj};localStorage.setItem("wl_max_bs",bs);localStorage.setItem("wl_max_fs",fs);localStorage.setItem("wl_max_sn",sn);localStorage.setItem("wl_max_cj",cj);updateMaxSummary();render()}
function restoreDefaultMaxes(){trainingMaxes={...DEFAULT_MAXES};["bs","fs","sn","cj"].forEach(k=>localStorage.setItem("wl_max_"+k,trainingMaxes[k]));initMaxInputs();render()}
function scaledPrescription(name,text){let out=text;const isBS=/Back Squat/i.test(name),isFS=/Front Squat/i.test(name);if(isBS){out=out.replace(/(\d+(?:\.\d+)?)(?:–(\d+(?:\.\d+)?))?\s*kg/g,(m,a,b)=>{const a2=round25(Number(a)*trainingMaxes.bs/112);if(b){const b2=round25(Number(b)*trainingMaxes.bs/112);return `${fmtKg(a2).replace(" kg","")}–${fmtKg(b2)}`}return fmtKg(a2)})}else if(isFS){out=out.replace(/(\d+(?:\.\d+)?)(?:–(\d+(?:\.\d+)?))?\s*kg/g,(m,a,b)=>{const a2=round25(Number(a)*trainingMaxes.fs/100);if(b){const b2=round25(Number(b)*trainingMaxes.fs/100);return `${fmtKg(a2).replace(" kg","")}–${fmtKg(b2)}`}return fmtKg(a2)})}return out}
function percentCalc(name,text){const max=/Clean & Jerk/i.test(name)?trainingMaxes.cj:/Snatch/i.test(name)?trainingMaxes.sn:0;if(!max)return"";const match=text.match(/(\d+(?:\.\d+)?)\s*[–-]\s*(\d+(?:\.\d+)?)%|(\d+(?:\.\d+)?)%/);if(!match)return"";let lo,hi;if(match[1]){lo=Number(match[1]);hi=Number(match[2])}else{lo=hi=Number(match[3])}const a=round25(max*lo/100),b=round25(max*hi/100);return a===b?`≈ ${fmtKg(a)}`:`≈ ${fmtKg(a)}–${fmtKg(b)}`}
let programStart=localStorage.getItem("wl_program_start")||"";
function parseDateOnly(s){const m=/^(\d{4})-(\d{2})-(\d{2})$/.exec(s||"");if(!m)return null;const y=Number(m[1]),mo=Number(m[2]),d=Number(m[3]);const dt=new Date(Date.UTC(y,mo-1,d));if(dt.getUTCFullYear()!==y||dt.getUTCMonth()!==mo-1||dt.getUTCDate()!==d)return null;return dt}
function addDaysUTC(dt,n){const x=new Date(dt.getTime());x.setUTCDate(x.getUTCDate()+n);return x}
function fmtDate(dt,withYear=false){if(!dt)return"";const y=dt.getUTCFullYear(),m=dt.getUTCMonth()+1,d=dt.getUTCDate();return withYear?`${y}年${m}月${d}日`:`${m}/${d}`}
function weekStartDate(weekNum){const base=parseDateOnly(programStart);return base?addDaysUTC(base,(weekNum-1)*7):null}
function trainingDate(weekNum,dayName){const offsets={"周一":0,"周二":1,"周四":3,"周五":4};const ws=weekStartDate(weekNum);return ws&&offsets[dayName]!==undefined?addDaysUTC(ws,offsets[dayName]):null}
function weekRangeText(weekNum){const ws=weekStartDate(weekNum);return ws?`${fmtDate(ws)}–${fmtDate(addDaysUTC(ws,6))}`:""}
function initSchedule(){const input=document.getElementById("programStart");if(programStart)input.value=programStart;document.getElementById("applyStartDate").addEventListener("click",()=>{const v=input.value;if(!parseDateOnly(v)){document.getElementById("scheduleHint").textContent="请选择有效日期。";return}programStart=v;localStorage.setItem("wl_program_start",v);updateScheduleHint();render()});updateScheduleHint()}
function updateScheduleHint(){const hint=document.getElementById("scheduleHint"),base=parseDateOnly(programStart);if(!base){hint.textContent="未设置开始日期。";return}const end=addDaysUTC(base,11*7+6);hint.textContent=`Week 1：${fmtDate(base,true)} 开始 · Week 12：${fmtDate(weekStartDate(12),true)}–${fmtDate(end,true)}`}
let currentWeek=Number(localStorage.getItem("wl_current_week")||1);const key=(w,d,i)=>`wl_${w}_${d}_${i}`;function saveField(k,v){localStorage.setItem(k,v)}function loadField(k){return localStorage.getItem(k)||""}
function weekStats(weekNum){const w=plan[weekNum-1];let total=0,done=0;Object.entries(w.days).forEach(([day,d])=>{if(d.main)d.main.forEach((_,i)=>{total++;if(loadField(key(weekNum,day,"main_"+i)+"_done")==="1")done++});if(d.choiceMain){total++;if(loadField(key(weekNum,day,"choiceMain_0")+"_done")==="1")done++;total++;if(loadField(key(weekNum,day,"choicePull_0")+"_done")==="1")done++}if(d.assist)d.assist.forEach((_,i)=>{total++;if(loadField(key(weekNum,day,"assist_"+i)+"_done")==="1")done++})});return{total,done,complete:total>0&&done===total}}
function updateCycleProgress(){let completed=0;for(let w=1;w<=plan.length;w++)if(weekStats(w).complete)completed++;const pct=Math.round(completed/plan.length*100),bar=document.getElementById("cycleProgressBar"),text=document.getElementById("cycleProgressText"),card=document.getElementById("cycleProgressCard");if(bar)bar.style.width=pct+"%";if(text)text.textContent=`${completed} / ${plan.length} 周`;if(card)card.classList.toggle("cycle-complete",completed===plan.length)}
function renderTabs(){const el=document.getElementById("weekTabs");el.innerHTML="";plan.forEach((_,i)=>{const b=document.createElement("button");b.className=[i+1===currentWeek?"active":"",weekStats(i+1).complete?"week-complete":""].filter(Boolean).join(" ");const range=weekRangeText(i+1);b.innerHTML=`W${i+1}${range?`<span class="tabdate">${range}</span>`:""}`;b.addEventListener("click",()=>{currentWeek=i+1;localStorage.setItem("wl_current_week",currentWeek);render()});el.appendChild(b)})}
function updateProgressOnly(){const st=weekStats(currentWeek),pct=st.total?Math.round(st.done/st.total*100):0;document.getElementById("progressBar").style.width=pct+"%";document.getElementById("progressText").textContent=`本周完成 ${st.done}/${st.total} · ${pct}%${st.complete?" · 整周完成 ✅":""}`;document.getElementById("weekBadge").textContent=st.complete?"✅ 完成":plan[currentWeek-1].phase;renderTabs();updateCycleProgress()}
function render(){renderTabs();const w=plan[currentWeek-1];document.getElementById("currentWeekLabel").textContent=`Week ${currentWeek}${weekRangeText(currentWeek)?" · "+weekRangeText(currentWeek):""}`;document.getElementById("phaseLabel").textContent=`阶段：${w.phase}`;document.getElementById("weekBadge").textContent=w.phase;const content=document.getElementById("content");content.innerHTML="";let total=0,done=0;
function addExercise(card,day,ex,i,section){total++;const id=key(currentWeek,day,section+"_"+i),checked=loadField(id+"_done")==="1";if(checked)done++;const row=document.createElement("div");row.className="exercise"+(checked?" done":"");const cb=document.createElement("input");cb.type="checkbox";cb.autocomplete="off";cb.checked=checked;cb.addEventListener("change",()=>{saveField(id+"_done",cb.checked?"1":"0");row.classList.toggle("done",cb.checked);updateProgressOnly()});const body=document.createElement("div"),displayRx=scaledPrescription(ex[0],ex[1]),calc=percentCalc(ex[0],ex[1]);body.innerHTML=`<div class="exname">${ex[0]}</div><div class="prescription">${displayRx}</div>${calc?`<div class="calc">${calc}</div>`:""}`;const fields=document.createElement("div");fields.className="fields";fields.innerHTML=`<input placeholder="实际重量/完成情况" value="${esc(loadField(id+"_actual"))}"><input placeholder="RPE" value="${esc(loadField(id+"_rpe"))}"><input placeholder="备注" value="${esc(loadField(id+"_note"))}">`;const ins=fields.querySelectorAll("input");ins[0].oninput=e=>saveField(id+"_actual",e.target.value);ins[1].oninput=e=>saveField(id+"_rpe",e.target.value);ins[2].oninput=e=>saveField(id+"_note",e.target.value);body.appendChild(fields);row.appendChild(cb);row.appendChild(body);card.appendChild(row)}
Object.entries(w.days).forEach(([day,d])=>{const card=document.createElement("div");card.className="card";const h=document.createElement("h3"),td=trainingDate(currentWeek,day);h.innerHTML=`${day}${td?`<span class="daydate">${fmtDate(td,true)}</span>`:""}`;h.style.marginTop="0";card.appendChild(h);if(d.main){const tag=document.createElement("div");tag.className="sectiontag";tag.textContent="主项";card.appendChild(tag);d.main.forEach((ex,i)=>addExercise(card,day,ex,i,"main"))}if(d.choiceMain){const tag=document.createElement("div");tag.className="sectiontag";tag.textContent="主项二选一";card.appendChild(tag);const ck=`wl_${currentWeek}_${day}_mainChoice`;let choice=loadField(ck)||"sn";const box=document.createElement("div");box.className="choicebox";box.innerHTML=`<label>今天主项</label><select autocomplete="off"><option value="sn" ${choice==="sn"?"selected":""}>抓举 Snatch</option><option value="cj" ${choice==="cj"?"selected":""}>挺举 Clean & Jerk</option></select>`;box.querySelector("select").addEventListener("change",e=>{saveField(ck,e.target.value);render()});card.appendChild(box);const name=choice==="sn"?"Snatch":"Clean & Jerk",rx=d.choiceMain[choice];addExercise(card,day,[name,rx],0,"choiceMain");const ptag=document.createElement("div");ptag.className="sectiontag";ptag.textContent="拉：二选一";card.appendChild(ptag);const pk=`wl_${currentWeek}_${day}_pullChoice`;let pchoice=loadField(pk)||"wide";const pbox=document.createElement("div");pbox.className="choicebox";pbox.innerHTML=`<label>今天拉</label><select autocomplete="off"><option value="wide" ${pchoice==="wide"?"selected":""}>宽拉 Snatch Pull</option><option value="narrow" ${pchoice==="narrow"?"selected":""}>窄拉 Clean Pull</option></select><div class="helper">拉的具体重量可在“实际重量/完成情况”里记录。</div>`;pbox.querySelector("select").addEventListener("change",e=>{saveField(pk,e.target.value);render()});card.appendChild(pbox);const pname=pchoice==="wide"?"Wide Pull / 宽拉":"Narrow Pull / 窄拉";addExercise(card,day,[pname,d.choicePull],0,"choicePull")}if(d.assist&&d.assist.length){const tag=document.createElement("div");tag.className="sectiontag";tag.textContent="辅助";card.appendChild(tag);d.assist.forEach((ex,i)=>addExercise(card,day,ex,i,"assist"))}content.appendChild(card)});
const pct=total?Math.round(done/total*100):0;document.getElementById("progressBar").style.width=pct+"%";const complete=total>0&&done===total;document.getElementById("progressText").textContent=`本周完成 ${done}/${total} · ${pct}%${complete?" · 整周完成 ✅":""}`;document.getElementById("weekBadge").textContent=complete?"✅ 完成":w.phase;renderTabs();updateCycleProgress()}
function esc(s){return String(s).replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;","'":"&#39;"}[m]))}
function resetWeek(){if(!confirm(`确定重置 Week ${currentWeek} 的勾选和记录吗？`))return;const prefix=`wl_${currentWeek}_`;Object.keys(localStorage).filter(k=>k.startsWith(prefix)).forEach(k=>localStorage.removeItem(k));render()}
function exportData(){let out=`12周举重训练记录\n${programStart?"Week 1 周一："+fmtDate(parseDateOnly(programStart),true)+"\n":""}\n`;plan.forEach((w,wi)=>{out+=`WEEK ${wi+1} — ${w.phase}${weekRangeText(wi+1)?" — "+weekRangeText(wi+1):""}\n`;Object.entries(w.days).forEach(([day,d])=>{out+=`${day}${trainingDate(wi+1,day)?" · "+fmtDate(trainingDate(wi+1,day),true):""}\n`;const emit=(ex,section,i)=>{const id=key(wi+1,day,section+"_"+i),done=loadField(id+"_done")==="1";out+=`${done?"✅":"☐"} ${ex[0]} — ${scaledPrescription(ex[0],ex[1])}${percentCalc(ex[0],ex[1])?" ("+percentCalc(ex[0],ex[1])+")":""}\n`;const a=loadField(id+"_actual"),r=loadField(id+"_rpe"),n=loadField(id+"_note");if(a||r||n)out+=`  实际:${a||"-"} | RPE:${r||"-"} | 备注:${n||"-"}\n`};if(d.main)d.main.forEach((ex,i)=>emit(ex,"main",i));if(d.choiceMain){const mchoice=loadField(`wl_${wi+1}_${day}_mainChoice`)||"sn",mname=mchoice==="sn"?"Snatch":"Clean & Jerk";out+=`  主项选择：${mname}\n`;emit([mname,d.choiceMain[mchoice]],"choiceMain",0);const pchoice=loadField(`wl_${wi+1}_${day}_pullChoice`)||"wide",pname=pchoice==="wide"?"Wide Pull / 宽拉":"Narrow Pull / 窄拉";out+=`  拉选择：${pname}\n`;emit([pname,d.choicePull],"choicePull",0)}if(d.assist)d.assist.forEach((ex,i)=>emit(ex,"assist",i))});out+="\n"});const blob=new Blob([out],{type:"text/plain;charset=utf-8"}),a=document.createElement("a");a.href=URL.createObjectURL(blob);a.download="12周举重训练记录.txt";a.click();setTimeout(()=>URL.revokeObjectURL(a.href),500)}
function jumpToday(){render();window.scrollTo({top:0,behavior:"smooth"})}
initMaxInputs();initSchedule();render();window.addEventListener("pageshow",()=>{setTimeout(()=>render(),60)});
