const KG_TO_LB=2.2046226218487757, LB_TO_KG=0.45359237;
const defs={kg:[25,20,15,10,5,2.5,1.25,0.5],lb:[45,35,25,10,5,2.5,1.25]};
const defaults={kg:{25:1,20:0,15:0,10:1,5:1,2.5:1,1.25:1,0.5:0},lb:{45:1,35:1,25:0,10:1,5:1,2.5:1,1.25:0}};
let mode=localStorage.getItem('bl_mode')||'nearest';
let inventory=loadInventory();
function key(u,w){return `${u}:${w}`}
function loadInventory(){const saved=localStorage.getItem('bl_inventory');if(saved){try{return JSON.parse(saved)}catch(e){}}const out={};for(const u of ['kg','lb'])for(const w of defs[u])out[key(u,w)]={enabled:(defaults[u][w]||0)>0,pairs:defaults[u][w]||1};return out}
function save(){localStorage.setItem('bl_inventory',JSON.stringify(inventory));localStorage.setItem('bl_mode',mode)}
function renderInventory(unit){const root=document.getElementById(unit+'Inventory');root.innerHTML='';for(const w of defs[unit]){const k=key(unit,w),st=inventory[k]||{enabled:false,pairs:1};const row=document.createElement('div');row.className='inv';row.innerHTML=`<input type="checkbox" ${st.enabled?'checked':''}><div><div class="invname">${w} ${unit.toUpperCase()}</div><div class="invsub">${st.pairs} 对 = ${st.pairs*2} 片</div></div><div class="stepper"><button type="button" class="minus">−</button><span class="count">${st.pairs}</span><button type="button" class="plus">+</button></div>`;const cb=row.querySelector('input');cb.onchange=()=>{st.enabled=cb.checked;inventory[k]=st;save();calculate()};row.querySelector('.minus').onclick=()=>{st.pairs=Math.max(1,st.pairs-1);inventory[k]=st;save();renderInventory(unit);calculate()};row.querySelector('.plus').onclick=()=>{st.pairs=Math.min(8,st.pairs+1);inventory[k]=st;save();renderInventory(unit);calculate()};root.appendChild(row)}}
function getBarKg(){const p=document.getElementById('barPreset').value;if(p==='20kg')return 20;if(p==='15kg')return 15;if(p==='45lb')return 45*LB_TO_KG;const v=Number(document.getElementById('customBar').value)||0;return document.getElementById('customBarUnit').value==='kg'?v:v*LB_TO_KG}
function targetKg(){const v=Number(document.getElementById('target').value);if(!Number.isFinite(v))return NaN;return document.getElementById('targetUnit').value==='kg'?v:v*LB_TO_KG}
function selectedTypes(){const a=[];for(const u of ['kg','lb'])for(const w of defs[u]){const st=inventory[key(u,w)];if(!st||!st.enabled||st.pairs<1)continue;const onePairKg=2*(u==='kg'?w:w*LB_TO_KG);a.push({unit:u,w,pairs:st.pairs,pairKg:onePairKg})}return a}
function solve(target,bar){const types=selectedTypes();const need=Math.max(0,target-bar);const cap=Math.max(need+100,500);let states=new Map([[0,{counts:new Array(types.length).fill(0),nplates:0}]]);for(let i=0;i<types.length;i++){const t=types[i],next=new Map(states);for(const [g,s] of states){for(let c=1;c<=t.pairs;c++){const kg=g/1000+c*t.pairKg;if(kg>cap)break;const ng=Math.round(kg*1000);const nc=s.counts.slice();nc[i]=c;const np=s.nplates+c*2;const prev=next.get(ng);if(!prev||np<prev.nplates)next.set(ng,{counts:nc,nplates:np})}}states=next}
 let best=null;for(const [g,s] of states){const plateKg=g/1000,actual=bar+plateKg,diff=actual-target;let valid=true,score;if(mode==='floor'){valid=diff<=1e-9;score=target-actual}else if(mode==='ceil'){valid=diff>=-1e-9;score=actual-target}else score=Math.abs(diff);if(!valid)continue;const cand={actual,diff,score,counts:s.counts,nplates:s.nplates,types};if(!best||cand.score<best.score-1e-9||(Math.abs(cand.score-best.score)<1e-9&&cand.nplates<best.nplates)||(Math.abs(cand.score-best.score)<1e-9&&cand.nplates===best.nplates&&cand.actual<best.actual))best=cand}
 return best}
function fmt(x,u){const v=u==='kg'?x:x*KG_TO_LB;return `${Number(v.toFixed(2))} ${u.toUpperCase()}`}
function plateColor(unit,w){if(unit==='kg'){if(w===25)return'#ef4444';if(w===20)return'#2563eb';if(w===15)return'#eab308';if(w===10)return'#16a34a';if(w===5)return'#f3f4f6';return'#9ca3af'}if(w===45)return'#374151';if(w===35)return'#6b7280';if(w===25)return'#ef4444';if(w===10)return'#16a34a';return'#d1d5db'}
function calculate(){const target=targetKg(),bar=getBarKg(),u=document.getElementById('targetUnit').value;if(!Number.isFinite(target)||target<=0)return;const r=solve(target,bar),actualEl=document.getElementById('actual'),deltaEl=document.getElementById('delta'),pr=document.getElementById('platesResult'),ex=document.getElementById('explain');document.getElementById('leftSleeve').innerHTML='';document.getElementById('rightSleeve').innerHTML='';if(!r){actualEl.textContent='无可行组合';deltaEl.textContent='—';pr.innerHTML='';ex.textContent='当前库存和取整模式下没有合法组合';return}actualEl.textContent=fmt(r.actual,u);const diff=u==='kg'?r.diff:r.diff*KG_TO_LB;deltaEl.textContent=Math.abs(diff)<0.0005?'精确':`${diff>0?'+':''}${Number(diff.toFixed(2))} ${u.toUpperCase()}`;deltaEl.className='delta '+(Math.abs(diff)<0.0005?'zero':diff>0?'pos':'neg');pr.innerHTML='';let chosen=[];r.types.forEach((t,i)=>{const c=r.counts[i];if(!c)return;chosen.push({t,c});const tag=document.createElement('div');tag.className='plateTag';tag.textContent=`${t.w} ${t.unit.toUpperCase()} × ${c} / side`;pr.appendChild(tag)});if(!chosen.length)pr.innerHTML='<div class="small">只用空杆</div>';for(const side of ['leftSleeve','rightSleeve']){const el=document.getElementById(side),arr=side==='leftSleeve'?chosen.slice().reverse():chosen;for(const {t,c} of arr)for(let j=0;j<c;j++){const p=document.createElement('div');p.className='miniPlate';p.style.background=plateColor(t.unit,t.w);p.style.width=Math.max(8,Math.min(24,8+t.w/3))+'px';el.appendChild(p)}}ex.textContent=`杠铃 ${fmt(bar,u)} · ${mode==='nearest'?'绝对误差最小':mode==='floor'?'不超过目标':'不低于目标'} · 共 ${r.nplates} 片`}
function setMode(m){mode=m;document.querySelectorAll('#modeButtons button').forEach(b=>b.classList.toggle('active',b.dataset.mode===m));save();calculate()}
document.querySelectorAll('#modeButtons button').forEach(b=>b.onclick=()=>setMode(b.dataset.mode));
document.querySelectorAll('[data-reset]').forEach(b=>b.onclick=()=>{const u=b.dataset.reset;for(const w of defs[u])inventory[key(u,w)]={enabled:(defaults[u][w]||0)>0,pairs:defaults[u][w]||1};save();renderInventory(u);calculate()});
for(const id of ['target','targetUnit','barPreset','customBar','customBarUnit'])document.getElementById(id).addEventListener('input',()=>{document.getElementById('customBarRow').classList.toggle('hidden',document.getElementById('barPreset').value!=='custom');calculate()});
['targetUnit','barPreset','customBarUnit'].forEach(id=>document.getElementById(id).addEventListener('change',()=>{document.getElementById('customBarRow').classList.toggle('hidden',document.getElementById('barPreset').value!=='custom');calculate()}));
renderInventory('kg');renderInventory('lb');setMode(mode);document.getElementById('customBarRow').classList.toggle('hidden',document.getElementById('barPreset').value!=='custom');
