(()=>{
const LB_TO_KG=0.45359237;
const PLATE_DEFS={kg:[25,20,15,10,5,2.5,1.25,0.5],lb:[45,35,25,10,5,2.5,1.25]};
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
function n(x,d=2){return Number(Number(x).toFixed(d))}
function esc(s){return String(s).replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;","'":"&#39;"}[m]))}
function getLoaderState(){let inventory={};try{inventory=JSON.parse(localStorage.getItem('bl_inventory')||'{}')}catch(e){};const mode=localStorage.getItem('bl_mode')||'nearest',barType=localStorage.getItem('bl_bar_type')||'20kg',useCollars=localStorage.getItem('bl_use_collars')==='1',collarWeight=Number(localStorage.getItem('bl_collar_weight')||2.5),collarUnit=localStorage.getItem('bl_collar_unit')||'kg';const bar=barType==='45lb'?45*LB_TO_KG:20,collarEach=Math.max(0,collarWeight)*(collarUnit==='lb'?LB_TO_KG:1);return{inventory,mode,barType,useCollars,collarWeight,collarUnit,base:bar+(useCollars?2*collarEach:0)}}
function loaderSolve(target,forcedMode){const st=getLoaderState(),mode=forcedMode||st.mode,types=[];for(const unit of ['kg','lb'])for(const w of PLATE_DEFS[unit]){const q=st.inventory[`${unit}:${w}`];if(q&&q.enabled&&q.pairs>0)types.push({unit,w,pairs:Number(q.pairs),pairKg:2*(unit==='kg'?w:w*LB_TO_KG)})}const cap=Math.max(target-st.base+100,500);let states=new Map([[0,{counts:new Array(types.length).fill(0),plates:0}]]);for(let i=0;i<types.length;i++){const t=types[i],next=new Map(states);for(const [g,s] of states){for(let c=1;c<=t.pairs;c++){const kg=g/1000+c*t.pairKg;if(kg>cap)break;const ng=Math.round(kg*1000),counts=s.counts.slice();counts[i]=c;const plates=s.plates+c*2,old=next.get(ng);if(!old||plates<old.plates)next.set(ng,{counts,plates})}}states=next}let best=null;for(const [g,s] of states){const actual=st.base+g/1000,diff=actual-target;let ok=true,score=Math.abs(diff);if(mode==='floor'){ok=diff<=1e-9;score=target-actual}else if(mode==='ceil'){ok=diff>=-1e-9;score=actual-target}if(!ok)continue;const c={actual,diff,score,counts:s.counts,plates:s.plates,types,base:st.base};if(!best||c.score<best.score-1e-9||(Math.abs(c.score-best.score)<1e-9&&c.plates<best.plates))best=c}return best}
function perSideMap(r){const m={};if(!r)return m;r.types.forEach((t,i)=>{if(r.counts[i])m[`${t.unit}:${t.w}`]=r.counts[i]});return m}
function changeText(fromTarget,toTarget){const a=loaderSolve(fromTarget,'nearest'),b=loaderSolve(toTarget,'nearest');if(!a||!b)return'当前库存下无法比较。';const A=perSideMap(a),B=perSideMap(b),add=[],remove=[];for(const k of new Set([...Object.keys(A),...Object.keys(B)])){const d=(B[k]||0)-(A[k]||0),[u,w]=k.split(':');if(d>0)add.push(`${w} ${u.toUpperCase()} ×${d}`);if(d<0)remove.push(`${w} ${u.toUpperCase()} ×${-d}`)}let parts=[];if(remove.length)parts.push('每侧卸 '+remove.join('、'));if(add.length)parts.push('每侧加 '+add.join('、'));if(!parts.length)parts.push('无需换片');return `${n(a.actual)} → ${n(b.actual)} kg：${parts.join('；')}`}
function ensureTabs(){const bar=$('#loaderTabBar');if(!bar||$('#tabToday'))return;const today=document.createElement('button');today.id='tabToday';today.textContent='今日训练';const tools=document.createElement('button');tools.id='tabTools';tools.textContent='工具';bar.append(today,tools);const originalPlan=$('#tabPlan').onclick,originalLoader=$('#tabLoader').onclick;$('#tabPlan').onclick=()=>{exitToday();hideTools();originalPlan&&originalPlan()};$('#tabLoader').onclick=()=>{exitToday();hideTools();originalLoader&&originalLoader()};today.onclick=()=>showToday();tools.onclick=()=>showTools()}
let todayObserver=null;
function exitToday(){const p=$('#planView');if(p)p.classList.remove('today-mode');$$('#content>.card').forEach(c=>c.classList.remove('today-day-hidden'));$('#todayBanner')?.remove();$('#tabToday')?.classList.remove('active')}
function localYmd(){const d=new Date();return new Date(Date.UTC(d.getFullYear(),d.getMonth(),d.getDate()))}
function parseYmd(s){const m=/^(\d{4})-(\d{2})-(\d{2})$/.exec(s||'');return m?new Date(Date.UTC(+m[1],+m[2]-1,+m[3])):null}
function showToday(){hideTools();const planView=$('#planView'),loaderView=$('#loaderView'),foot=$('.footerbar');planView?.classList.remove('loader-hidden');loaderView?.classList.add('loader-hidden');foot?.classList.remove('loader-hidden');$('#tabPlan')?.classList.remove('active');$('#tabLoader')?.classList.remove('active');$('#tabTools')?.classList.remove('active');$('#tabToday')?.classList.add('active');const start=parseYmd(localStorage.getItem('wl_program_start'));const today=localYmd();let week=null,dayName=null,msg='';if(start){const diff=Math.floor((today-start)/86400000);week=Math.floor(diff/7)+1;const off=((diff%7)+7)%7;dayName={0:'周一',1:'周二',3:'周四',4:'周五'}[off]||null;if(week<1||week>12){msg='今天不在当前 12 周周期内。';week=null}else if(!dayName)msg='今天没有排定训练。'}else msg='先在“周期日期”里设置 Week 1 周一。';if(week){try{currentWeek=week;localStorage.setItem('wl_current_week',week);render()}catch(e){const b=$$('#weekTabs button')[week-1];b&&b.click()}}planView?.classList.add('today-mode');applyTodayFilter(dayName,msg,week);if(todayObserver)todayObserver.disconnect();const root=$('#content');if(root){todayObserver=new MutationObserver(()=>applyTodayFilter(dayName,msg,week));todayObserver.observe(root,{childList:true,subtree:true})}}
function applyTodayFilter(dayName,msg,week){const p=$('#planView');if(!p||!p.classList.contains('today-mode'))return;$('#todayBanner')?.remove();const b=document.createElement('div');b.id='todayBanner';b.className='today-banner';b.innerHTML=`<b>${dayName?`今日 ${dayName} · Week ${week}`:'今日训练'}</b><div class="small">${esc(msg||'只显示今天的训练动作。')}</div>`;const content=$('#content');content?.before(b);$$('#content>.card').forEach(c=>{const h=c.querySelector('h3')?.textContent||'';c.classList.toggle('today-day-hidden',!dayName||!h.trim().startsWith(dayName))})}
function ensureTools(){if($('#toolsView'))return;const v=document.createElement('div');v.id='toolsView';v.className='wrap loader-hidden';v.innerHTML=`<div class="tools-card"><div class="weektitle"><div><h2 style="font-size:18px;margin:0">训练工具</h2><div class="small">计时器、Quick Load、e1RM、备份都在这里。</div></div><span class="badge">Tools</span></div></div><div class="tools-card"><h3 style="margin-top:0">休息计时器默认值</h3><div class="tools-grid"><div><label>深蹲 / 重主项 (秒)</label><input id="timerHeavy" type="number" min="30" step="15"></div><div><label>抓挺 / 拉 (秒)</label><input id="timerOly" type="number" min="30" step="15"></div><div><label>辅助 (秒)</label><input id="timerAssist" type="number" min="30" step="15"></div></div></div><div class="tools-card"><h3 style="margin-top:0">PR / e1RM</h3><div class="tools-grid" id="e1rmBest"></div><div style="overflow:auto;margin-top:10px"><table class="history-table"><thead><tr><th>日期</th><th>动作</th><th>重量×次数</th><th>RPE</th><th>e1RM</th></tr></thead><tbody id="e1rmRows"></tbody></table></div></div><div class="tools-card"><h3 style="margin-top:0">数据备份</h3><div class="small" style="margin-bottom:8px">备份包含训练记录、Max、日期、配重 inventory、卡扣、工具设置。</div><div class="backup-row"><button id="backupExport">导出 JSON 备份</button><label>导入 JSON<input id="backupImport" type="file" accept="application/json,.json"></label></div></div>`;document.body.insertBefore(v,$('.footerbar'));for(const [id,key,def] of [['timerHeavy','wl_timer_heavy',180],['timerOly','wl_timer_oly',120],['timerAssist','wl_timer_assist',90]]){const el=$('#'+id);el.value=localStorage.getItem(key)||def;el.onchange=()=>localStorage.setItem(key,String(Math.max(30,Number(el.value)||def)))}$('#backupExport').onclick=exportBackup;$('#backupImport').onchange=importBackup;renderE1RM()}
function showTools(){ensureTools();exitToday();$('#planView')?.classList.add('loader-hidden');$('#loaderView')?.classList.add('loader-hidden');$('#toolsView')?.classList.remove('loader-hidden');$('.footerbar')?.classList.add('loader-hidden');$('#tabPlan')?.classList.remove('active');$('#tabLoader')?.classList.remove('active');$('#tabToday')?.classList.remove('active');$('#tabTools')?.classList.add('active');renderE1RM()}
function hideTools(){$('#toolsView')?.classList.add('loader-hidden');$('#tabTools')?.classList.remove('active')}
function ensureTimer(){if($('#restTimer'))return;const d=document.createElement('div');d.id='restTimer';d.className='timer-float hidden';d.innerHTML='<div class="timer-sub" id="timerLabel">休息</div><div class="timer-main" id="timerDisplay">0:00</div><div class="timer-controls"><button id="timerMinus">−30</button><button id="timerPause">暂停</button><button id="timerPlus">+30</button><button id="timerClose">×</button></div>';document.body.appendChild(d);$('#timerMinus').onclick=()=>adjustTimer(-30);$('#timerPlus').onclick=()=>adjustTimer(30);$('#timerPause').onclick=toggleTimer;$('#timerClose').onclick=stopTimer}
let timerEnd=0,timerRemain=0,timerId=null,timerPaused=false;
function timerSecondsFor(row){const name=row.querySelector('.exname')?.textContent||'';if(/Squat/i.test(name))return Number(localStorage.getItem('wl_timer_heavy')||180);if(/Snatch|Clean & Jerk|Pull/i.test(name))return Number(localStorage.getItem('wl_timer_oly')||120);return Number(localStorage.getItem('wl_timer_assist')||90)}
function startTimer(sec,label){ensureTimer();clearInterval(timerId);timerPaused=false;timerRemain=sec;timerEnd=Date.now()+sec*1000;$('#timerLabel').textContent=`休息 · ${label}`;$('#restTimer').classList.remove('hidden');$('#timerPause').textContent='暂停';tickTimer();timerId=setInterval(tickTimer,250)}
function tickTimer(){if(timerPaused)return;timerRemain=Math.max(0,Math.ceil((timerEnd-Date.now())/1000));const m=Math.floor(timerRemain/60),s=timerRemain%60;$('#timerDisplay').textContent=`${m}:${String(s).padStart(2,'0')}`;if(timerRemain<=0){clearInterval(timerId);timerId=null;$('#timerDisplay').textContent='完成';try{navigator.vibrate&&navigator.vibrate([150,80,150])}catch(e){};try{const A=window.AudioContext||window.webkitAudioContext;if(A){const a=new A(),o=a.createOscillator(),g=a.createGain();o.connect(g);g.connect(a.destination);g.gain.value=.04;o.frequency.value=880;o.start();o.stop(a.currentTime+.18)}}catch(e){}}}
function adjustTimer(d){timerRemain=Math.max(0,timerRemain+d);if(!timerPaused)timerEnd=Date.now()+timerRemain*1000;tickTimer()}
function toggleTimer(){if(timerPaused){timerPaused=false;timerEnd=Date.now()+timerRemain*1000;$('#timerPause').textContent='暂停'}else{timerPaused=true;timerRemain=Math.max(0,Math.ceil((timerEnd-Date.now())/1000));$('#timerPause').textContent='继续'}tickTimer()}
function stopTimer(){clearInterval(timerId);timerId=null;$('#restTimer')?.classList.add('hidden')}
function hookCheckboxTimer(e){const cb=e.target;if(!(cb instanceof HTMLInputElement)||cb.type!=='checkbox'||!cb.checked)return;const row=cb.closest('.exercise');if(!row)return;const name=row.querySelector('.exname')?.textContent||'训练';startTimer(timerSecondsFor(row),name)}
function addWarmupLoadButtons(){if(!window.BarbellLoader)return;$$('.warmup-steps span').forEach(s=>{if(s.querySelector('.warmup-load-btn'))return;const m=(s.textContent||'').match(/(\d+(?:\.\d+)?)\s*kg/i);if(!m)return;const w=Number(m[1]),b=document.createElement('button');b.type='button';b.className='warmup-load-btn';b.textContent='配重';b.onclick=()=>window.BarbellLoader.open(w);s.appendChild(b)});$$('.warmup-box').forEach(box=>{if(box.querySelector('.warmup-plan-all'))return;const vals=$$('.warmup-steps span',box)})}
function addQuickButtons(){if(!window.BarbellLoader)return;$$('.exercise').forEach(row=>{if(row.querySelector('.quick-load-btn'))return;const p=row.querySelector('.prescription');const m=(p?.textContent||'').match(/(\d+(?:\.\d+)?)\s*kg/i);if(!m)return;const target=Number(m[1]),wrap=document.createElement('div');wrap.className='feature-actions';const q=document.createElement('button');q.type='button';q.className='feature-btn quick-load-btn';q.textContent='下一组怎么换片';q.onclick=()=>showQuick(target);const w=document.createElement('button');w.type='button';w.className='feature-btn';w.textContent='热身配重清单';w.onclick=()=>showWarmupPlan(row,target);wrap.append(q);if(/Squat/i.test(row.querySelector('.exname')?.textContent||''))wrap.append(w);row.querySelector('.prescription')?.insertAdjacentElement('afterend',wrap)})}
function ensureFeatureModal(){if($('#featureModal'))return;const m=document.createElement('div');m.id='featureModal';m.className='feature-modal hidden';m.innerHTML='<div class="feature-sheet"><div class="weektitle"><h3 id="featureTitle">工具</h3><button class="feature-btn" id="featureClose">关闭</button></div><div id="featureBody"></div></div>';document.body.appendChild(m);$('#featureClose').onclick=()=>m.classList.add('hidden');m.onclick=e=>{if(e.target===m)m.classList.add('hidden')}}
function showQuick(target){ensureFeatureModal();const last=Number(localStorage.getItem('wl_current_bar_target')||0),body=$('#featureBody');$('#featureTitle').textContent='下一组怎么换片';if(last>0){body.innerHTML=`<div class="quick-box"><b>${esc(changeText(last,target))}</b></div><div class="current-load">当前记录：${last} kg → 目标 ${target} kg</div>`}else body.innerHTML='<div class="quick-box">还没有记录“当前杠上重量”。先打开一次配重方案，然后点“设为当前杠上重量”。</div>';const r=loaderSolve(target,'nearest');if(r)body.innerHTML+=`<div class="feature-actions"><button class="feature-btn primary-mini" id="quickOpen">查看 ${n(r.actual)} kg 配重</button><button class="feature-btn" id="quickSet">直接设为当前</button></div>`;$('#quickOpen')?.addEventListener('click',()=>window.BarbellLoader.open(target));$('#quickSet')?.addEventListener('click',()=>{localStorage.setItem('wl_current_bar_target',String(target));$('#featureModal').classList.add('hidden')});$('#featureModal').classList.remove('hidden')}
function warmupTargets(row,target){const name=row.querySelector('.exname')?.textContent||'';const compact=/Paused|Front Squat/i.test(name)&&row.closest('.card')?.querySelectorAll('.exercise')[0]!==row;const ps=compact?[.6,.8,.9]:[.5,.65,.8,.9];return ps.map(p=>Math.round(target*p/2.5)*2.5).filter((x,i,a)=>x>0&&a.indexOf(x)===i)}
function showWarmupPlan(row,target){ensureFeatureModal();$('#featureTitle').textContent='热身配重清单';const vals=warmupTargets(row,target),body=$('#featureBody');let html='';for(const v of vals){const r=loaderSolve(v,'nearest');html+=`<div class="warmup-plan-row"><b>${v} kg</b>${r?` <span class="small">→ 实际 ${n(r.actual)} kg</span>`:''}<div class="chips">${r?r.types.map((t,i)=>r.counts[i]?`<span class="chip">${t.w} ${t.unit.toUpperCase()} ×${r.counts[i]}/侧</span>`:'').join(''):'无可行组合'}</div></div>`}html+=`<div class="warmup-plan-row"><b>正式组 ${target} kg</b></div>`;body.innerHTML=html;$('#featureModal').classList.remove('hidden')}
function injectCurrentButton(){const modal=$('#loaderModal .loader-sheet');if(!modal||$('#setCurrentBar'))return;const b=document.createElement('button');b.id='setCurrentBar';b.className='primary';b.style.cssText='width:100%;margin-top:10px';b.textContent='设为当前杠上重量';b.onclick=()=>{const t=Number($('#loaderModal')?.dataset.target||0);if(t>0){localStorage.setItem('wl_current_bar_target',String(t));b.textContent=`已设为当前：${t} kg`;setTimeout(()=>b.textContent='设为当前杠上重量',1200)}};modal.appendChild(b)}
function captureE1RM(e){const inp=e.target;if(!(inp instanceof HTMLInputElement))return;const row=inp.closest('.exercise');if(!row)return;const fields=[...row.querySelectorAll('.fields input')];if(!fields.length||inp!==fields[0]&&inp!==fields[1])return;const name=row.querySelector('.exname')?.textContent?.trim()||'';if(!/Back Squat|Front Squat|Snatch|Clean & Jerk/i.test(name))return;const weight=Number((fields[0].value.match(/\d+(?:\.\d+)?/)||[])[0]);if(!(weight>0))return;const rx=row.querySelector('.prescription')?.textContent||'',matches=[...rx.matchAll(/×\s*(\d+)/g)],reps=matches.length?Number(matches[matches.length-1][1]):1,rpe=Number(fields[1].value)||0,rir=rpe>=6&&rpe<=10?10-rpe:0,effective=Math.max(1,reps+rir),e1=weight*(1+effective/30);let hist=[];try{hist=JSON.parse(localStorage.getItem('wl_e1rm_history')||'[]')}catch(err){}const rec={ts:Date.now(),date:new Date().toISOString().slice(0,10),week:Number(localStorage.getItem('wl_current_week')||1),name,weight,reps,rpe:rpe||null,e1rm:n(e1,1)};const fp=`${rec.week}|${name}|${weight}|${reps}|${rpe}`;hist=hist.filter(x=>`${x.week}|${x.name}|${x.weight}|${x.reps}|${x.rpe||0}`!==fp);hist.push(rec);hist=hist.slice(-300);localStorage.setItem('wl_e1rm_history',JSON.stringify(hist));renderE1RM()}
function renderE1RM(){const best=$('#e1rmBest'),rows=$('#e1rmRows');if(!best||!rows)return;let hist=[];try{hist=JSON.parse(localStorage.getItem('wl_e1rm_history')||'[]')}catch(e){}const lifts=['Back Squat','Front Squat','Snatch','Clean & Jerk'];best.innerHTML=lifts.map(l=>{const vals=hist.filter(x=>x.name.includes(l));const b=vals.length?Math.max(...vals.map(x=>Number(x.e1rm)||0)):0;return `<div class="metric"><span class="small">${l}</span><b>${b?b.toFixed(1)+' kg':'—'}</b></div>`}).join('');rows.innerHTML=hist.slice().reverse().slice(0,30).map(x=>`<tr><td>${x.date}</td><td>${esc(x.name)}</td><td>${x.weight}×${x.reps}</td><td>${x.rpe||'-'}</td><td>${x.e1rm} kg</td></tr>`).join('')}
function exportBackup(){const data={version:1,exportedAt:new Date().toISOString(),localStorage:{}};for(let i=0;i<localStorage.length;i++){const k=localStorage.key(i);if(k&&(k.startsWith('wl_')||k.startsWith('bl_')))data.localStorage[k]=localStorage.getItem(k)}const blob=new Blob([JSON.stringify(data,null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`weightlifting-backup-${new Date().toISOString().slice(0,10)}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
function importBackup(e){const f=e.target.files?.[0];if(!f)return;const r=new FileReader();r.onload=()=>{try{const d=JSON.parse(r.result);if(!d.localStorage||typeof d.localStorage!=='object')throw new Error('bad');if(!confirm('导入会覆盖当前训练 App 的本地设置和记录，继续吗？'))return;Object.entries(d.localStorage).forEach(([k,v])=>{if(k.startsWith('wl_')||k.startsWith('bl_'))localStorage.setItem(k,String(v))});location.reload()}catch(err){alert('备份文件无效。')}};r.readAsText(f)}
function periodicInject(){ensureTabs();ensureTools();ensureTimer();injectCurrentButton();addWarmupLoadButtons();addQuickButtons()}
document.addEventListener('change',hookCheckboxTimer,true);document.addEventListener('blur',captureE1RM,true);const obs=new MutationObserver(()=>{clearTimeout(window.__featureInject);window.__featureInject=setTimeout(periodicInject,30)});window.addEventListener('DOMContentLoaded',()=>{periodicInject();const c=$('#content');if(c)obs.observe(c,{childList:true,subtree:true})});window.addEventListener('pageshow',()=>setTimeout(periodicInject,80));
})();