(()=>{
const LB_TO_KG=0.45359237;
const defs={kg:[25,20,15,10,5,2.5,1.25,0.5],lb:[45,35,25,10,5,2.5,1.25]};
const $=s=>document.querySelector(s);
let counts={};
try{counts=JSON.parse(localStorage.getItem('bl_reverse_counts')||'{}')||{}}catch(e){counts={}}
function key(unit,w){return `${unit}:${w}`}
function save(){localStorage.setItem('bl_reverse_counts',JSON.stringify(counts))}
function barKg(){return ($('#loaderBarType')?.value||localStorage.getItem('bl_bar_type')||'20kg')==='45lb'?45*LB_TO_KG:20}
function collarEachKg(){const w=Math.max(0,Number($('#loaderCollarWeight')?.value||localStorage.getItem('bl_collar_weight')||2.5));const u=$('#loaderCollarUnit')?.value||localStorage.getItem('bl_collar_unit')||'kg';return w*(u==='lb'?LB_TO_KG:1)}
function useCollars(){const el=$('#loaderUseCollars');return el?el.checked:localStorage.getItem('bl_use_collars')==='1'}
function fmt(x){return Number(Number(x).toFixed(2))}
function total(){let side=0;for(const unit of ['kg','lb'])for(const w of defs[unit])side+=(Number(counts[key(unit,w)])||0)*(unit==='kg'?w:w*LB_TO_KG);const base=barKg()+(useCollars()?2*collarEachKg():0);return{base,side,total:base+2*side}}
function paintTotal(){const out=$('#reverseTotal'),detail=$('#reverseBreakdown');if(!out)return;const r=total();out.textContent=`${fmt(r.total)} kg`;if(detail)detail.textContent=`基础 ${fmt(r.base)} kg + 两侧挂片 ${fmt(r.side*2)} kg`}
function render(unit){const root=$(unit==='kg'?'#reverseKg':'#reverseLb');if(!root)return;root.innerHTML='';for(const w of defs[unit]){const k=key(unit,w),n=Math.max(0,Number(counts[k])||0),row=document.createElement('div');row.className='reverse-plate';row.innerHTML=`<div><b>${w} ${unit.toUpperCase()}</b><div class="small">每侧</div></div><div class="reverse-step"><button type="button">−</button><strong>${n}</strong><button type="button">+</button></div>`;const bs=row.querySelectorAll('button');bs[0].onclick=()=>{counts[k]=Math.max(0,n-1);save();render(unit);paintTotal()};bs[1].onclick=()=>{counts[k]=Math.min(12,n+1);save();render(unit);paintTotal()};root.appendChild(row)}}
function show(which){const target=which==='target';$('#loaderTargetSubView')?.classList.toggle('loader-hidden',!target);$('#loaderReverseSubView')?.classList.toggle('loader-hidden',target);$('#loaderSubTarget')?.classList.toggle('active',target);$('#loaderSubReverse')?.classList.toggle('active',!target);if(!target)paintTotal()}
function init(){const view=$('#loaderView');if(!view||$('#loaderSubTabs'))return false;const css=document.createElement('link');css.rel='stylesheet';css.href='loader-reverse.css?v=1';document.head.appendChild(css);const current=[...view.children];const nav=document.createElement('div');nav.id='loaderSubTabs';nav.className='loader-card loader-subtabs';nav.innerHTML='<button id="loaderSubTarget" class="active" type="button">目标重量 → 配片</button><button id="loaderSubReverse" type="button">挂片 → 总重量</button>';const target=document.createElement('div');target.id='loaderTargetSubView';current.forEach(x=>target.appendChild(x));const reverse=document.createElement('div');reverse.id='loaderReverseSubView';reverse.className='loader-hidden';reverse.innerHTML=`<div class="loader-card"><div class="weektitle"><div><h2 style="font-size:18px;margin:0">现在杠上有多重？</h2><div class="small">数量按每侧输入；自动乘两侧，再加杠铃和卡扣。</div></div><button id="reverseClear" type="button">清空</button></div><div class="reverse-result"><span>当前总重量</span><b id="reverseTotal">—</b><div class="small" id="reverseBreakdown"></div></div></div><div class="loader-card"><h3 style="margin-top:0">每侧 KG Plates</h3><div class="reverse-plate-grid" id="reverseKg"></div></div><div class="loader-card"><h3 style="margin-top:0">每侧 LB Plates</h3><div class="reverse-plate-grid" id="reverseLb"></div></div>`;view.append(nav,target,reverse);$('#loaderSubTarget').onclick=()=>show('target');$('#loaderSubReverse').onclick=()=>show('reverse');$('#reverseClear').onclick=()=>{counts={};save();render('kg');render('lb');paintTotal()};['#loaderBarType','#loaderUseCollars','#loaderCollarWeight','#loaderCollarUnit'].forEach(s=>{const el=$(s);if(el){el.addEventListener('change',paintTotal);el.addEventListener('input',paintTotal)}});render('kg');render('lb');paintTotal();return true}
function boot(){if(init())return;let n=0;const id=setInterval(()=>{n++;if(init()||n>30)clearInterval(id)},100)}
window.addEventListener('DOMContentLoaded',boot);window.addEventListener('pageshow',()=>setTimeout(init,120));
})();