(()=>{
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const ACTIVE='wl_active_session',HISTORY='wl_session_history';
let tickId=null;
function pad(n){return String(n).padStart(2,'0')}
function ymd(d=new Date()){return `${d.getFullYear()}-${pad(d.getMonth()+1)}-${pad(d.getDate())}`}
function clock(ts){const d=new Date(ts);return `${pad(d.getHours())}:${pad(d.getMinutes())}`}
function duration(sec){sec=Math.max(0,Math.round(sec||0));const h=Math.floor(sec/3600),m=Math.floor(sec%3600/60),s=sec%60;return h?`${h}:${pad(m)}:${pad(s)}`:`${m}:${pad(s)}`}
function loadActive(){try{return JSON.parse(localStorage.getItem(ACTIVE)||'null')}catch(e){return null}}
function saveActive(s){if(s)localStorage.setItem(ACTIVE,JSON.stringify(s));else localStorage.removeItem(ACTIVE)}
function loadHistory(){try{const h=JSON.parse(localStorage.getItem(HISTORY)||'[]');return Array.isArray(h)?h:[]}catch(e){return[]}}
function saveHistory(h){localStorage.setItem(HISTORY,JSON.stringify(h.slice(-200)))}
function elapsedMs(s,now=Date.now()){if(!s)return 0;const end=s.pausedAt||now;return Math.max(0,end-s.startAt-(s.pausedMs||0))}
function rowMeta(row){const h=row?.closest('.card')?.querySelector('h3')?.textContent?.trim()||'';const day=(h.match(/周[一二三四五六日]/)||[])[0]||h||'训练';let week=Number(localStorage.getItem('wl_current_week')||1);try{week=Number(currentWeek)||week}catch(e){}return{day,week}}
function newSession(row){const now=Date.now(),meta=rowMeta(row);return{id:String(now),date:ymd(),week:meta.week,day:meta.day,startAt:now,lastActive:now,pausedMs:0,pausedAt:null}}
function archive(s,endAt){if(!s)return;const stop=endAt||Date.now(),dur=Math.round(elapsedMs(s,stop)/1000);if(dur<1)return;const h=loadHistory();h.push({id:s.id,date:s.date,week:s.week,day:s.day,startAt:s.startAt,endAt:stop,durationSec:dur});saveHistory(h)}
function touch(row){let s=loadActive(),now=Date.now();if(s&&s.date!==ymd()){archive(s,s.lastActive||now);s=null}if(!s)s=newSession(row);if(s.pausedAt){s.pausedMs=(s.pausedMs||0)+(now-s.pausedAt);s.pausedAt=null}s.lastActive=now;saveActive(s);ensureStopwatch();renderStopwatch();renderReview()}
function pauseResume(){const s=loadActive();if(!s)return;const now=Date.now();if(s.pausedAt){s.pausedMs=(s.pausedMs||0)+(now-s.pausedAt);s.pausedAt=null}else s.pausedAt=now;s.lastActive=now;saveActive(s);renderStopwatch();renderReview()}
function finish(){const s=loadActive();if(!s)return;if(!confirm('结束本次训练并保存用时？'))return;const now=Date.now();if(s.pausedAt){s.pausedMs=(s.pausedMs||0)+(now-s.pausedAt);s.pausedAt=null}archive(s,now);saveActive(null);renderStopwatch();renderReview()}
function startManual(){if(loadActive())return;const s=newSession(null);saveActive(s);ensureStopwatch();renderStopwatch();renderReview()}
function ensureStopwatch(){if($('#workoutStopwatch'))return;const d=document.createElement('div');d.id='workoutStopwatch';d.className='workout-stopwatch session-hidden';d.innerHTML='<div><div class="session-small">训练计时</div><div class="session-time" id="sessionTime">0:00</div></div><div class="session-float-actions"><button id="sessionPause" type="button">暂停</button><button id="sessionFinish" type="button">结束</button></div>';document.body.appendChild(d);$('#sessionPause').onclick=pauseResume;$('#sessionFinish').onclick=finish}
function renderStopwatch(){ensureStopwatch();const s=loadActive(),box=$('#workoutStopwatch');if(!s){box.classList.add('session-hidden');return}box.classList.remove('session-hidden');$('#sessionTime').textContent=duration(elapsedMs(s)/1000);$('#sessionPause').textContent=s.pausedAt?'继续':'暂停'}
function ensureReview(){if($('#reviewView'))return;const v=document.createElement('div');v.id='reviewView';v.className='wrap loader-hidden';v.innerHTML=`<div class="review-card"><div class="weektitle"><div><h2 style="font-size:18px;margin:0">训练复盘</h2><div class="small">记录每次训练的日期、开始结束时间和总用时。</div></div><span class="badge">Log</span></div></div><div class="review-card" id="reviewCurrent"></div><div class="review-card"><div class="weektitle"><h3 style="margin:0">训练历史</h3><button type="button" id="clearSessions" class="review-small-btn">清空历史</button></div><div id="reviewHistory"></div></div>`;document.body.insertBefore(v,$('.footerbar'));$('#clearSessions').onclick=()=>{if(confirm('确定清空训练用时历史吗？')){saveHistory([]);renderReview()}}}
function renderReview(){ensureReview();const s=loadActive(),cur=$('#reviewCurrent'),hist=$('#reviewHistory');if(s){cur.innerHTML=`<div class="review-current-top"><div><div class="small">进行中的训练</div><b>Week ${s.week} · ${s.day} · ${s.date}</b></div><div class="review-live">${duration(elapsedMs(s)/1000)}</div></div><div class="review-actions"><button type="button" id="reviewPause">${s.pausedAt?'继续':'暂停'}</button><button type="button" class="review-end" id="reviewFinish">结束并保存</button></div>`;$('#reviewPause').onclick=pauseResume;$('#reviewFinish').onclick=finish}else{cur.innerHTML='<div class="review-empty">当前没有进行中的训练。第一次点热身组或正式组按钮时会自动开始计时。</div><button type="button" class="review-start" id="reviewStart">手动开始训练</button>';$('#reviewStart').onclick=startManual}const h=loadHistory().slice().reverse();hist.innerHTML=h.length?h.map(x=>`<div class="review-row"><div><b>${x.date} · Week ${x.week} · ${x.day}</b><div class="small">${clock(x.startAt)} → ${clock(x.endAt)}</div></div><div class="review-duration">${duration(x.durationSec)}</div><button type="button" class="review-delete" data-session-id="${x.id}">删除</button></div>`).join(''):'<div class="review-empty">还没有训练记录。</div>';$$('.review-delete',hist).forEach(b=>b.onclick=()=>{saveHistory(loadHistory().filter(x=>x.id!==b.dataset.sessionId));renderReview()})}
function hideReview(){$('#reviewView')?.classList.add('loader-hidden');$('#tabToday')?.classList.remove('active')}
function showReview(){ensureReview();$('#planView')?.classList.add('loader-hidden');$('#loaderView')?.classList.add('loader-hidden');$('#toolsView')?.classList.add('loader-hidden');$('.footerbar')?.classList.add('loader-hidden');$$('#loaderTabBar button').forEach(b=>b.classList.remove('active'));$('#tabToday')?.classList.add('active');$('#reviewView')?.classList.remove('loader-hidden');renderReview()}
function installTab(){const t=$('#tabToday');if(!t)return;t.textContent='训练复盘';t.onclick=showReview;for(const id of ['tabPlan','tabLoader','tabTools']){const b=$('#'+id);if(!b||b.dataset.reviewWrapped)return;const old=b.onclick;b.onclick=()=>{hideReview();old&&old()};b.dataset.reviewWrapped='1'}}
function hideOldCountdown(){const r=$('#restTimer');if(r)r.classList.add('session-force-hide');const heavy=$('#timerHeavy');const card=heavy?.closest('.tools-card');if(card)card.style.display='none';const intro=$('#toolsView .tools-card .small');if(intro&&/计时器|Quick Load/.test(intro.textContent))intro.textContent='组数记录、e1RM、训练复盘和备份。'}
function init(){ensureStopwatch();ensureReview();installTab();hideOldCountdown();renderStopwatch();renderReview();clearInterval(tickId);tickId=setInterval(()=>{renderStopwatch();if(!$('#reviewView')?.classList.contains('loader-hidden'))renderReview()},1000)}
window.TrainingSession={touch,finish,pauseResume};
window.addEventListener('DOMContentLoaded',()=>setTimeout(init,120));window.addEventListener('pageshow',()=>setTimeout(init,160));
})();
