(()=>{
const $$=(s,r=document)=>[...r.querySelectorAll(s)];
const clean=s=>String(s||'').trim().replace(/\s+/g,' ');
function currentWeekNum(){try{return Number(currentWeek)||Number(localStorage.getItem('wl_current_week')||1)}catch(e){return Number(localStorage.getItem('wl_current_week')||1)}}
function dayOf(row){return clean(row.closest('.card')?.querySelector('h3')?.textContent||'').replace(/\s*\d{4}年.*$/,'')}
function exerciseKey(row,type){const week=currentWeekNum(),day=dayOf(row),name=clean(row.querySelector('.exname')?.textContent),rx=clean(row.querySelector('.prescription')?.textContent);return `wl_settrack_${week}_${encodeURIComponent(day)}_${encodeURIComponent(name)}_${encodeURIComponent(rx)}_${type}`}
function parseSets(rx){let total=0;for(const m of String(rx||'').matchAll(/(\d+)\s*[×x]\s*(\d+)/g))total+=Number(m[1])||0;return total}
function ensureProxy(row){let p=row.querySelector('.set-timer-proxy');if(!p){p=document.createElement('input');p.type='checkbox';p.className='set-timer-proxy';p.tabIndex=-1;row.appendChild(p)}return p}
function startExistingTimer(row){const p=ensureProxy(row);p.checked=false;p.click();p.checked=false}
function syncOriginalDone(row,count,total){const cb=[...row.children].find(x=>x instanceof HTMLInputElement&&x.type==='checkbox'&&!x.classList.contains('set-timer-proxy'));if(!cb)return;if(count>=total&&!cb.checked)cb.click();else if(count<total&&cb.checked)cb.click()}
function addFormalTracker(row){if(row.querySelector('.set-tracker'))return;const rx=row.querySelector('.prescription')?.textContent||'',total=parseSets(rx);if(!total)return;row.classList.add('has-set-tracker');const body=row.querySelector(':scope > div');if(!body)return;const key=exerciseKey(row,'work'),box=document.createElement('div');box.className='set-tracker';box.innerHTML='<div class="set-tracker-top"><span class="set-tracker-count"></span><span class="small">每完成一组自动开始休息计时</span></div><div class="set-tracker-actions"><button type="button" class="set-minus">− 一组</button><button type="button" class="set-add">完成一组</button></div>';body.appendChild(box);const countEl=box.querySelector('.set-tracker-count'),minus=box.querySelector('.set-minus'),add=box.querySelector('.set-add');let count=Math.min(total,Math.max(0,Number(localStorage.getItem(key)||0)));function paint(){countEl.textContent=`正式组 ${count} / ${total} 组`;countEl.classList.toggle('complete',count>=total);minus.disabled=count<=0;add.disabled=count>=total;localStorage.setItem(key,String(count));syncOriginalDone(row,count,total)}minus.onclick=()=>{count=Math.max(0,count-1);paint()};add.onclick=()=>{if(count>=total)return;count++;paint();startExistingTimer(row)};paint()}
function warmupRow(box){let n=box.nextElementSibling;while(n&&!n.classList.contains('exercise'))n=n.nextElementSibling;return n&&n.classList.contains('exercise')?n:null}
function addWarmupTracker(box){if(box.nextElementSibling?.classList?.contains('warmup-record'))return;const row=warmupRow(box);if(!row)return;const steps=$$('.warmup-steps span',box).filter(s=>!/^正式组/.test(clean(s.textContent)));if(!steps.length)return;const key=exerciseKey(row,'warmup');let done=[];try{done=JSON.parse(localStorage.getItem(key)||'[]')}catch(e){};if(!Array.isArray(done))done=[];const rec=document.createElement('div');rec.className='warmup-record';const head=document.createElement('div');head.className='warmup-record-head';const label=document.createElement('span'),hint=document.createElement('span');hint.className='small';hint.textContent='点一下记录该热身组';head.append(label,hint);const list=document.createElement('div');list.className='warmup-record-steps';rec.append(head,list);box.insertAdjacentElement('afterend',rec);function save(){localStorage.setItem(key,JSON.stringify(done))}function paintHead(){const c=done.filter(Boolean).length;label.textContent=`热身 ${c} / ${steps.length} 组`}steps.forEach((s,i)=>{const chip=document.createElement('div');chip.className='warmup-record-step';const text=document.createElement('span');text.textContent=clean(s.childNodes[0]?.textContent||s.textContent).replace(/配重$/,'').trim();const btn=document.createElement('button');btn.type='button';function paint(){chip.classList.toggle('done',!!done[i]);btn.textContent=done[i]?'✓':'○'}btn.onclick=()=>{done[i]=!done[i];paint();paintHead();save();if(done[i])startExistingTimer(row)};chip.append(text,btn);list.appendChild(chip);paint()});paintHead();save()}
function cleanQuickLoad(){document.querySelectorAll('.quick-load-btn,#setCurrentBar').forEach(el=>el.style.display='none');const t=document.querySelector('#toolsView .tools-card .small');if(t&&/Quick Load/.test(t.textContent))t.textContent='计时器、组数记录、e1RM、备份都在这里。'}
function inject(){cleanQuickLoad();$$('.exercise').forEach(addFormalTracker);$$('.warmup-box').forEach(addWarmupTracker)}
let busy=false;function schedule(){if(busy)return;busy=true;setTimeout(()=>{busy=false;inject()},60)}
window.addEventListener('DOMContentLoaded',()=>{inject();const root=document.getElementById('content');if(root)new MutationObserver(schedule).observe(root,{childList:true,subtree:true})});window.addEventListener('pageshow',()=>setTimeout(inject,120));
})();
