const CACHE="wl-plan-v11-progress-inject";
const ASSETS=["./","./index.html","./manifest.webmanifest","./icon.svg"];
const STYLE='<style id="cycle-progress-style">button.week-complete{background:#dcfce7!important;color:#166534!important;border:1px solid #86efac!important}button.week-complete.active{background:#166534!important;color:#fff!important}.cycle-complete{border-color:#86efac!important;background:#f0fdf4!important}.cycle-progress-label{display:flex;justify-content:space-between;align-items:center;gap:10px}.cycle-progress-label strong{font-size:17px}</style>';
const SCRIPT='<script>(function(){function stat(w){var ww=plan[w-1],t=0,dn=0;Object.entries(ww.days).forEach(function(pair){var day=pair[0],x=pair[1];if(x.main)x.main.forEach(function(_,i){t++;if(localStorage.getItem("wl_"+w+"_"+day+"_main_"+i+"_done")==="1")dn++;});if(x.choiceMain){t++;if(localStorage.getItem("wl_"+w+"_"+day+"_choiceMain_0_done")==="1")dn++;t++;if(localStorage.getItem("wl_"+w+"_"+day+"_choicePull_0_done")==="1")dn++;}if(x.assist)x.assist.forEach(function(_,i){t++;if(localStorage.getItem("wl_"+w+"_"+day+"_assist_"+i+"_done")==="1")dn++;});});return{total:t,done:dn,complete:t>0&&dn===t};}function ensure(){if(!document.getElementById("cycleProgressCard")){var tabs=document.getElementById("weekTabs");if(!tabs)return;var c=document.createElement("div");c.className="card";c.id="cycleProgressCard";c.innerHTML="<div class=\"cycle-progress-label\"><div><strong>12\u5468\u5468\u671f\u8fdb\u5ea6</strong><div class=\"small\">\u6574\u5468\u6240\u6709\u9879\u76ee\u90fd\u6253\u52fe\u540e\uff0c\u8be5\u5468\u624d\u8ba1\u4e3a\u5b8c\u6210\u3002</div></div><span class=\"badge\" id=\"cycleProgressText\">0 / 12 \u5468</span></div><div class=\"progress\"><div id=\"cycleProgressBar\"></div></div>";tabs.parentNode.insertBefore(c,tabs);}}function update(){ensure();var count=0;for(var w=1;w<=plan.length;w++)if(stat(w).complete)count++;var text=document.getElementById("cycleProgressText"),bar=document.getElementById("cycleProgressBar"),card=document.getElementById("cycleProgressCard");if(text)text.textContent=count+" / "+plan.length+" \u5468";if(bar)bar.style.width=Math.round(count/plan.length*100)+"%";if(card)card.classList.toggle("cycle-complete",count===plan.length);var buttons=document.querySelectorAll("#weekTabs button");buttons.forEach(function(b,i){b.classList.toggle("week-complete",stat(i+1).complete);});}document.addEventListener("change",function(){setTimeout(update,50)});window.addEventListener("pageshow",function(){setTimeout(update,80)});setInterval(update,700);setTimeout(update,100);})();</script>';
self.addEventListener("install",e=>{self.skipWaiting();e.waitUntil(caches.open(CACHE).then(c=>c.addAll(ASSETS)))});
self.addEventListener("activate",e=>e.waitUntil(caches.keys().then(keys=>Promise.all(keys.filter(k=>k!==CACHE).map(k=>caches.delete(k)))).then(()=>self.clients.claim())));
self.addEventListener("fetch",e=>{
  if(e.request.mode==="navigate"){
    e.respondWith(fetch(e.request,{cache:"no-store"}).then(async r=>{const ct=r.headers.get("content-type")||"";if(!ct.includes("text/html"))return r;let h=await r.text();if(!h.includes("cycle-progress-style"))h=h.replace("</head>",STYLE+"</head>").replace("</body>",SCRIPT+"</body>");return new Response(h,{status:r.status,statusText:r.statusText,headers:r.headers});}).catch(()=>caches.match("./index.html")));
    return;
  }
  e.respondWith(fetch(e.request).catch(()=>caches.match(e.request)));
});